# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: FlyCloud-Blog
subtitle: never give up!
description: live and learn!
email: damonflycloud@126.com
author: flycloud
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: damonflycloud.info
#enforce_ssl: damonflycloud.info
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight: #代码高亮
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: 127.0.0.1
logger: false
logger_format:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10 ##首页默认10篇文章标题 如果值为0不分页
pagination_dir: page

archive_generator:
  yearly: true ##生成年视图
  monthly: true ##生成月视图
  per_page: 0

category_generator:
  per_page: 0 ###分类页面默认10篇文章

tag_generator:
   per_page: 0 ##标签分类页面默认10篇文章

# Disqus
disqus_shortname:

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  #repo: https://github.com/damonflycloud/damonflycloud.github.io.git
  repo: git@github.com:damonflycloud/damonflycloud.github.io.git
  branch: master
  message: flycloud-blog
